name: Deploy container to Azure

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: credit-app-suml
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: siemiata/suml-project:latest
